# Generated by Django 6.0.6 on 2026-06-17 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobpost'),
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='requirements',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Minimum experience required in years'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('REMOTE', 'Remote')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills_required',
            field=models.TextField(default='Python, Django', help_text='Comma-separated list of required technical competencies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='Remote', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active / Accepting Applications'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
