# Generated by Django 6.0.6 on 2026-06-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_application_job_remove_jobpost_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_snapshot', models.FileField(blank=True, help_text='Tracks the active candidate resume snapshot at the exact millisecond of submission.', null=True, upload_to='application_resumes_snapshots/')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied / Pending Review'), ('REVIEWING', 'In Profile Screening'), ('INTERVIEW', 'Interview Phase Scheduled'), ('OFFER', 'Job Offer Extended'), ('REJECTED', 'Application Rejected')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobpost')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='core_jobapp_status_398880_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applied_at'], name='core_jobapp_applied_aea653_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'candidate_profile')},
        ),
    ]
