# Generated by Django 6.0.6 on 2026-06-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_adminactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ats_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
