# Generated by Django 6.0.6 on 2026-06-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jobapplication_ats_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-ats_score', '-applied_at']},
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='idx_app_status',
            old_name='core_jobapp_status_398880_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='idx_app_applied_at',
            old_name='core_jobapp_applied_aea653_idx',
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['ats_score'], name='idx_app_ats_score'),
        ),
    ]
