# Generated by Django 6.0.6 on 2026-06-29 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible / Validation Clear'), ('QUEUED', 'Call Queued in Pipeline'), ('IN_PROGRESS', 'Outbound Dialing Active'), ('COMPLETED', 'Screening Completed successfully'), ('FAILED', 'Handshake Failure / Carrier Dropped'), ('BLOCKED', 'Outside Permissible Business Hours')], default='ELIGIBLE', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('scheduled_window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('execution_logs', models.TextField(default='Engine initialized.')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_call_tracking', to='core.jobapplication')),
            ],
        ),
    ]
