# Generated by Django 6.0.6 on 2026-06-30 08:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aicalltracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INITIATED', 'Trunk Line Established'), ('RINGING', 'Device Alerting Carrier'), ('CONNECTED', 'Candidate Answered / Live Dialogue'), ('COMPLETED', 'Interview Finalized Normally'), ('ABANDONED', 'Candidate Hung Up Early'), ('NO_ANSWER', 'Carrier Timeout / Voice Mail Hit')], default='INITIATED', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('overall_sentiment_score', models.FloatField(blank=True, null=True)),
                ('raw_full_transcript', models.TextField(blank=True, default='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='core.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephony_provider', models.CharField(default='Twilio', max_length=50)),
                ('provider_call_sid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sip_response_code', models.IntegerField(blank=True, null=True)),
                ('trigger_reason', models.CharField(default='Automated threshold system shortlist rule match.', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('carrier_logs', models.TextField(blank=True, default='')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_ai_calls', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_log', to='core.aiinterviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.aiinterviewsession')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='AIAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_speech_text', models.TextField()),
                ('confidence_score', models.FloatField(default=1.0)),
                ('structured_analysis', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='core.aiquestion')),
            ],
        ),
    ]
