# Generated by Django 6.0.6 on 2026-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aiinterviewsession_aicalllog_aiquestion_aianswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(default='Python Full Stack Developer', max_length=100)),
                ('category', models.CharField(choices=[('INTRO', 'Introduction & Background'), ('EXPERIENCE', 'Professional Experience Audit'), ('SKILLS', 'Role-Specific Technical Competency'), ('AVAILABILITY', 'Availability & Shift Logistics'), ('SALARY', 'Compensation & Salary Expectations')], max_length=20)),
                ('question_key', models.CharField(max_length=100, unique=True)),
                ('template_text', models.TextField()),
                ('sequence_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
    ]
