# Generated by Django 6.0.6 on 2026-07-01 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aiquestiontemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianswer',
            name='latency_ms',
        ),
        migrations.RemoveField(
            model_name='aianswer',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='aianswer',
            name='completeness_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aianswer',
            name='final_evaluation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='keyword_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
    ]
