# Generated by Django 6.0.6 on 2026-07-01 11:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_aianswer_latency_ms_remove_aianswer_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRRecruiterAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_name', models.CharField(max_length=150)),
                ('target_role', models.CharField(default='Technical Interviewer', max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AIInterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interview', to='core.jobapplication')),
                ('availability_slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booked_interview', to='core.hrrecruiteravailability')),
            ],
        ),
    ]
