# Generated by Django 6.0.6 on 2026-07-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_hrrecruiteravailability_aiinterviewschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_stage', models.CharField(choices=[('24_HOUR', '24 Hours Before Alert'), ('1_HOUR', '1 Hour Final Alert')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Delivered successfully'), ('FAILED', 'Transmission Failure')], max_length=20)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('interview_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='core.aiinterviewschedule')),
            ],
            options={
                'unique_together': {('interview_schedule', 'reminder_stage')},
            },
        ),
    ]
