# Generated by Django 6.0.6 on 2026-07-02 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_aireminderlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICandidateEvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_match_score', models.FloatField(default=0.0)),
                ('voice_screening_score', models.FloatField(default=0.0)),
                ('executive_summary', models.TextField()),
                ('identified_strengths', models.JSONField(default=list)),
                ('identified_risks', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_report', to='core.jobapplication')),
                ('generated_by', models.ForeignKey(limit_choices_to={'role': 'EMPLOYER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
