# Generated by Django 6.0.6 on 2026-07-06 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aicandidateevaluationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditTrailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Information Log'), ('WARNING', 'Operational Warning / Retry'), ('ERROR', 'System Exception / Security Breach Attempt')], default='INFO', max_length=10)),
                ('category', models.CharField(choices=[('USER_ACTION', 'Standard Candidate/Recruiter Interaction'), ('ADMIN_ACTION', 'Platform Governance Setting Updates'), ('AI_ENGINE', 'Automated Profiling & Voice Telemetry Evaluations'), ('SECURITY', 'Authentication & Access Controls Tracking')], default='USER_ACTION', max_length=15)),
                ('action_signature', models.CharField(max_length=255)),
                ('detailed_payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Audit Trail Log',
                'verbose_name_plural': 'System Audit Trail Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
