# Generated by Django 6.0.6 on 2026-07-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_subscriptionplan_paymenttransaction_billinghistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_premium_insights',
            field=models.BooleanField(default=False),
        ),
    ]
