# Generated by Django 6.0.6 on 2026-07-21 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0022_financialauditlog_transaction_refundlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiinterviewsession',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveIndex(
            model_name='jobapplication',
            name='idx_app_status',
        ),
        migrations.RemoveIndex(
            model_name='jobapplication',
            name='idx_app_applied_at',
        ),
        migrations.RemoveIndex(
            model_name='jobapplication',
            name='idx_app_ats_score',
        ),
        migrations.RemoveIndex(
            model_name='jobpost',
            name='core_jobpos_status_d8405c_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobpost',
            name='core_jobpos_created_9c7f64_idx',
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='executed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='aianswer',
            name='final_evaluation_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='aicalltracking',
            name='scheduled_window_start',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aicalltracking',
            name='status',
            field=models.CharField(choices=[('ELIGIBLE', 'Eligible / Validation Clear'), ('QUEUED', 'Call Queued in Pipeline'), ('IN_PROGRESS', 'Outbound Dialing Active'), ('COMPLETED', 'Screening Completed successfully'), ('FAILED', 'Handshake Failure / Carrier Dropped'), ('BLOCKED', 'Outside Permissible Business Hours')], db_index=True, default='ELIGIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='aicandidateevaluationreport',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='aiinterviewschedule',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aiinterviewschedule',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiinterviewsession',
            name='started_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aiinterviewsession',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Trunk Line Established'), ('RINGING', 'Device Alerting Carrier'), ('CONNECTED', 'Candidate Answered / Live Dialogue'), ('COMPLETED', 'Interview Finalized Normally'), ('ABANDONED', 'Candidate Hung Up Early'), ('NO_ANSWER', 'Carrier Timeout / Voice Mail Hit')], db_index=True, default='INITIATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiquestion',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aiquestiontemplate',
            name='category',
            field=models.CharField(choices=[('INTRO', 'Introduction & Background'), ('EXPERIENCE', 'Professional Experience Audit'), ('SKILLS', 'Role-Specific Technical Competency'), ('AVAILABILITY', 'Availability & Shift Logistics'), ('SALARY', 'Compensation & Salary Expectations')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='aiquestiontemplate',
            name='question_key',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='aiquestiontemplate',
            name='role_type',
            field=models.CharField(db_index=True, default='Python Full Stack Developer', max_length=100),
        ),
        migrations.AlterField(
            model_name='aireminderlog',
            name='dispatched_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='applicationauditlog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='issued_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYER', 'Employer'), ('CANDIDATE', 'Candidate')], db_index=True, default='CANDIDATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='financialauditlog',
            name='event_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='financialauditlog',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Suspicious Activity'), ('CRITICAL', 'Payment Failure / Systemic Risk')], db_index=True, default='INFO', max_length=15),
        ),
        migrations.AlterField(
            model_name='financialauditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hrrecruiteravailability',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='hrrecruiteravailability',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='hrrecruiteravailability',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], db_index=True, default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='ats_score',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied / Pending Review'), ('REVIEWING', 'In Profile Screening'), ('INTERVIEW', 'Interview Phase Scheduled'), ('OFFER', 'Job Offer Extended'), ('REJECTED', 'Application Rejected')], db_index=True, default='APPLIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(db_index=True, default='Remote', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active / Accepting Applications'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Transaction Completed Successfully'), ('FAILED', 'Transaction Declined/Aborted'), ('PENDING', 'Awaiting Webhook Confirmation')], db_index=True, default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='refundlog',
            name='refunded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('FREE', 'Free Tier'), ('PRO', 'Pro Professional Tier'), ('ENTERPRISE', 'Enterprise Suite')], db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='systemaudittraillog',
            name='action_signature',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='systemaudittraillog',
            name='category',
            field=models.CharField(choices=[('USER_ACTION', 'Standard Candidate/Recruiter Interaction'), ('ADMIN_ACTION', 'Platform Governance Setting Updates'), ('AI_ENGINE', 'Automated Profiling & Voice Telemetry Evaluations'), ('SECURITY', 'Authentication & Access Controls Tracking')], db_index=True, default='USER_ACTION', max_length=15),
        ),
        migrations.AlterField(
            model_name='systemaudittraillog',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Information Log'), ('WARNING', 'Operational Warning / Retry'), ('ERROR', 'System Exception / Security Breach Attempt')], db_index=True, default='INFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemaudittraillog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Payment Completed'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Fully Refunded')], db_index=True, default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stripe_charge_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='current_period_end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active Subscription'), ('PAST_DUE', 'Payment Overdue Gracetrack'), ('CANCELLED', 'Cancelled Plan Account')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['admin', '-executed_at'], name='idx_admin_action_date'),
        ),
        migrations.AddIndex(
            model_name='aicalltracking',
            index=models.Index(fields=['status', 'scheduled_window_start'], name='idx_aicall_status_sched'),
        ),
        migrations.AddIndex(
            model_name='aiinterviewsession',
            index=models.Index(fields=['application', 'status'], name='idx_aisess_app_status'),
        ),
        migrations.AddIndex(
            model_name='aiquestion',
            index=models.Index(fields=['session', 'sequence_order'], name='idx_aiq_session_seq'),
        ),
        migrations.AddIndex(
            model_name='aiquestiontemplate',
            index=models.Index(fields=['role_type', 'category'], name='idx_tmpl_role_cat'),
        ),
        migrations.AddIndex(
            model_name='applicationauditlog',
            index=models.Index(fields=['application', '-changed_at'], name='idx_audit_app_date'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['is_deleted', 'user'], name='idx_cand_deleted_user'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'role'], name='idx_user_active_role'),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['is_deleted', 'company_name'], name='idx_emp_deleted_name'),
        ),
        migrations.AddIndex(
            model_name='financialauditlog',
            index=models.Index(fields=['severity', '-timestamp'], name='idx_finaudit_sev_time'),
        ),
        migrations.AddIndex(
            model_name='hrrecruiteravailability',
            index=models.Index(fields=['status', 'start_time'], name='idx_avail_status_start'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', '-ats_score'], name='idx_app_status_ats'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='idx_app_job_status'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['candidate_profile', 'status'], name='idx_app_cand_status'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['-applied_at'], name='idx_app_applied_desc'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', '-created_at'], name='idx_job_status_created'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['location', 'status'], name='idx_job_loc_status'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['job_type', 'status'], name='idx_job_type_status'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', '-processed_at'], name='idx_pay_user_date'),
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['candidate', '-saved_at'], name='idx_saved_cand_date'),
        ),
        migrations.AddIndex(
            model_name='systemaudittraillog',
            index=models.Index(fields=['severity', '-timestamp'], name='idx_audit_sev_time'),
        ),
        migrations.AddIndex(
            model_name='systemaudittraillog',
            index=models.Index(fields=['category', '-timestamp'], name='idx_audit_cat_time'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='idx_txn_status_date'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'current_period_end'], name='idx_sub_status_end'),
        ),
    ]
